version: '3.8'

services:
  ylab_app:
    container_name: my_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - my_network
    ports:
      - "8000:8000"
    command: bash -c "alembic upgrade head && python main.py"
    depends_on:
      my_redis:
        condition: service_healthy
      my_postgres_db:
        condition: service_healthy

  my_redis:
    container_name: my_redis
    image: redis:6.2.6-alpine
    expose:
      - 6379
    ports:
      - "9000:6379"
    networks:
      - my_network

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 20s
      retries: 100

  my_postgres_db:
    container_name: my_postgres_db
    image: postgres:latest
    volumes:
      - /mnt/small/share/cont/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - my_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 5s
      timeout: 20s
      retries: 100

networks:
  my_network:

volumes:
  postgres_data: